name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install Frontend Deps
        run: cd client && npm install

      - name: Lint Frontend
        run: cd client && npm run lint

      - name: Install Backend Deps
        run: cd server && npm install

      - name: Lint Backend
        run: cd server && npm run lint

      - name: Build UI
        run: cd server && npm run build:ui

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Strike **/build from .gitignore
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        run: sed -i '/^\*\*\/build$/d' .gitignore

      - name: Heroku Deploy
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "young-lowlands-97512"
          heroku_email: "aubrey.nicoll@gmail.com"
          appdir: "server"
          healthcheck: "https://young-lowlands-97512.herokuapp.com/health"
          checkstring: "OK"
          rollbackonhealthcheckfailed: true

      - name: Slack notification
        if: always()
        uses: 8398a7/action-slack@b6a4c791ce0c137843eb11e038f855cf567014dc
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
